sudo: required 
language: node_js
node_js:
    - 17
    
services: 
    - docker
before_install: 
    - docker build -t EricJobs3/my-app -f Dockerfile.dev .
script:     
    - docker run -e CI=true EricJobs3/my-app npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1" ### AWS region of your choice
  app: "my-app" ### Your EB App name
  env: "Myapp-env" ### Your EB App environment name
  bucket_name: "elasticbeanstalk-us-east-1-366423825935" ### S3 bucket name
  bucket_path: "EBApptest" ### S3 folder name under S3 bucket above
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
